package org.eclipse.imp.leg.parser;

public interface LEGParsersym {
    public final static int
      TK_boolean = 11,
      TK_double = 12,
      TK_else = 26,
      TK_false = 16,
      TK_if = 21,
      TK_int = 13,
      TK_return = 22,
      TK_true = 17,
      TK_void = 27,
      TK_while = 23,
      TK_IDENTIFIER = 10,
      TK_NUMBER = 18,
      TK_DoubleLiteral = 19,
      TK_COMMA = 24,
      TK_SEMICOLON = 1,
      TK_PLUS = 2,
      TK_MINUS = 3,
      TK_ASSIGN = 25,
      TK_TIMES = 4,
      TK_DIVIDE = 5,
      TK_GREATER = 6,
      TK_LESS = 7,
      TK_EQUAL = 8,
      TK_NOTEQUAL = 9,
      TK_LEFTPAREN = 14,
      TK_RIGHTPAREN = 15,
      TK_LEFTBRACE = 20,
      TK_RIGHTBRACE = 28,
      TK_EOF_TOKEN = 29,
      TK_SINGLE_LINE_COMMENT = 31,
      TK_MissingExpression = 30,
      TK_ERROR_TOKEN = 32;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "SEMICOLON",
                 "PLUS",
                 "MINUS",
                 "TIMES",
                 "DIVIDE",
                 "GREATER",
                 "LESS",
                 "EQUAL",
                 "NOTEQUAL",
                 "IDENTIFIER",
                 "boolean",
                 "double",
                 "int",
                 "LEFTPAREN",
                 "RIGHTPAREN",
                 "false",
                 "true",
                 "NUMBER",
                 "DoubleLiteral",
                 "LEFTBRACE",
                 "if",
                 "return",
                 "while",
                 "COMMA",
                 "ASSIGN",
                 "else",
                 "void",
                 "RIGHTBRACE",
                 "EOF_TOKEN",
                 "MissingExpression",
                 "SINGLE_LINE_COMMENT",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
